
const seed={products:[{id:1,title:"شومیز مدل A",price:850000,stock:12,category:"پوشاک"},{id:2,title:"کیف مدل B",price:1250000,stock:8,category:"کیف"},{id:3,title:"شال مدل C",price:390000,stock:25,category:"اکسسوری"}],customers:[{id:1,name:"مریم",phone:"09120000001",city:"تهران",orders:2},{id:2,name:"سارا",phone:"09120000002",city:"کرج",orders:1}],orders:[{id:"ORD-1001",customer:"مریم",total:1700000,status:"آماده ارسال",payment:"پرداخت شد"},{id:"ORD-1002",customer:"سارا",total:390000,status:"جدید",payment:"بیعانه"}],suppliers:[{id:1,name:"عمده‌فروشی پوشاک بهار",city:"تهران",category:"پوشاک زنانه"},{id:2,name:"پخش کیف آریا",city:"تبریز",category:"کیف و اکسسوری"}],wholesaleCatalog:[{id:1,title:"شومیز عمده مدل X",wholesalePrice:520000,moq:6,stock:120},{id:2,title:"کیف عمده مدل Y",wholesalePrice:780000,moq:4,stock:50}],b2bOrders:[{id:"B2B-2001",seller:"بوتیک رز",product:"شومیز عمده مدل X",qty:12,total:6240000,status:"درحال آماده‌سازی"}]};
function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}} function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
const state={products:load('demo_products',seed.products),customers:load('demo_customers',seed.customers),orders:load('demo_orders',seed.orders),cart:load('demo_cart',[]),suppliers:load('demo_suppliers',seed.suppliers),wholesaleCatalog:load('demo_wholesaleCatalog',seed.wholesaleCatalog),b2bOrders:load('demo_b2bOrders',seed.b2bOrders)};
function fmt(n){return new Intl.NumberFormat('fa-IR').format(n)+' تومان'}
function renderStore(){const g=document.getElementById('productGrid'); if(!g) return; const q=(document.getElementById('searchStore')?.value||'').trim(); g.innerHTML=''; state.products.filter(p=>!q||p.title.includes(q)).forEach(p=>{const el=document.createElement('div'); el.className='product'; el.innerHTML=`<h3>${p.title}</h3><div class="muted">${p.category||''}</div><div class="price">${fmt(p.price)}</div><div class="muted">موجودی: ${p.stock}</div><button onclick="addToCart(${p.id})">افزودن به سبد</button>`; g.appendChild(el)}); updateCartBadge()}
function addToCart(id){const p=state.products.find(x=>x.id===id); if(!p) return; const e=state.cart.find(x=>x.id===id); if(e)e.qty+=1; else state.cart.push({id:p.id,title:p.title,price:p.price,qty:1}); save('demo_cart',state.cart); updateCartBadge()}
function updateCartBadge(){const el=document.getElementById('cartCount'); if(el) el.textContent=state.cart.reduce((a,b)=>a+b.qty,0)}
function openCart(){renderCart(); document.getElementById('cartModal')?.classList.remove('hidden')} function closeCart(){document.getElementById('cartModal')?.classList.add('hidden')}
function renderCart(){const w=document.getElementById('cartItems'); if(!w) return; w.innerHTML=''; let total=0; state.cart.forEach((item,idx)=>{total+=item.price*item.qty; const row=document.createElement('div'); row.className='card'; row.innerHTML=`${item.title} — ${item.qty} × ${fmt(item.price)} <button onclick="removeCart(${idx})">حذف</button>`; w.appendChild(row)}); const t=document.getElementById('cartTotal'); if(t) t.textContent=fmt(total)}
function removeCart(idx){state.cart.splice(idx,1); save('demo_cart',state.cart); renderCart(); updateCartBadge()} function goCheckout(){closeCart(); document.getElementById('checkoutSection')?.classList.remove('hidden')}
function submitOrder(){const name=document.getElementById('buyerName')?.value?.trim(); const phone=document.getElementById('buyerPhone')?.value?.trim(); const address=document.getElementById('buyerAddress')?.value?.trim(); if(!name||!phone){alert('نام و شماره را وارد کن'); return} const total=state.cart.reduce((a,b)=>a+b.price*b.qty,0); const id='ORD-'+Math.floor(1000+Math.random()*9000); state.orders.unshift({id,customer:name,total,status:'جدید',payment:'در انتظار پرداخت'}); const ex=state.customers.find(c=>c.phone===phone); if(ex) ex.orders+=1; else state.customers.unshift({id:Date.now(),name,phone,city:address||'-',orders:1}); save('demo_orders',state.orders); save('demo_customers',state.customers); state.cart=[]; save('demo_cart',state.cart); document.getElementById('checkoutMsg').innerHTML=`<p>سفارش ثبت شد. کد سفارش: <strong>${id}</strong></p>`; updateCartBadge()}
function trackOrder(){const code=document.getElementById('trackCode')?.value?.trim(); const res=document.getElementById('trackResult'); const o=state.orders.find(x=>x.id===code); if(!res)return; if(!o){res.innerHTML='<p>سفارشی با این کد پیدا نشد.</p>'; return} res.innerHTML=`<div class="card"><p>کد: ${o.id}</p><p>مشتری: ${o.customer}</p><p>مبلغ: ${fmt(o.total)}</p><p>وضعیت: ${o.status}</p><p>پرداخت: ${o.payment}</p></div>`}
function renderSeller(){const s=document.getElementById('sellerStats'); if(!s) return; const totalSales=state.orders.reduce((a,b)=>a+b.total,0); s.innerHTML=[['محصول',state.products.length],['سفارش',state.orders.length],['فروش کل',fmt(totalSales)],['مشتری تکراری',state.customers.filter(c=>c.orders>1).length]].map(x=>`<div class="stat"><div>${x[0]}</div><div class="n">${x[1]}</div></div>`).join(''); document.getElementById('sellerProducts').innerHTML=state.products.map(p=>`<tr><td>${p.title}</td><td>${fmt(p.price)}</td><td>${p.stock}</td></tr>`).join(''); document.getElementById('sellerOrders').innerHTML=state.orders.map(o=>`<tr><td>${o.id}</td><td>${o.customer}</td><td>${fmt(o.total)}</td><td>${o.status}</td><td>${o.payment}</td></tr>`).join(''); document.getElementById('sellerCustomers').innerHTML=state.customers.map(c=>`<tr><td>${c.name}</td><td>${c.phone}</td><td>${c.city}</td><td>${c.orders}</td></tr>`).join('')}
function addProduct(){const title=document.getElementById('newProductTitle')?.value?.trim(); const price=Number(document.getElementById('newProductPrice')?.value||0); const stock=Number(document.getElementById('newProductStock')?.value||0); if(!title||!price){alert('نام و قیمت لازم است'); return} state.products.unshift({id:Date.now(),title,price,stock,category:'جدید'}); save('demo_products',state.products); renderSeller()}
function renderSupplier(){const s=document.getElementById('supplierStats'); if(!s) return; s.innerHTML=[['تأمین‌کننده',state.suppliers.length],['محصول عمده',state.wholesaleCatalog.length],['سفارش B2B',state.b2bOrders.length],['موجودی کل',state.wholesaleCatalog.reduce((a,b)=>a+b.stock,0)]].map(x=>`<div class="stat"><div>${x[0]}</div><div class="n">${x[1]}</div></div>`).join(''); document.getElementById('supplierCatalog').innerHTML=state.wholesaleCatalog.map(i=>`<tr><td>${i.title}</td><td>${fmt(i.wholesalePrice)}</td><td>${i.moq}</td><td>${i.stock}</td></tr>`).join(''); document.getElementById('supplierOrders').innerHTML=state.b2bOrders.map(o=>`<tr><td>${o.id}</td><td>${o.seller}</td><td>${o.product}</td><td>${o.qty}</td><td>${fmt(o.total)}</td><td>${o.status}</td></tr>`).join(''); document.getElementById('supplierList').innerHTML=state.suppliers.map(s=>`<div class="card"><h3>${s.name}</h3><p>${s.city}</p><p>${s.category}</p></div>`).join('')}
document.addEventListener('DOMContentLoaded',()=>{if(document.getElementById('productGrid')){renderStore(); document.getElementById('searchStore')?.addEventListener('input',renderStore)} if(document.getElementById('sellerStats')) renderSeller(); if(document.getElementById('supplierStats')) renderSupplier();});
